"""warehouse model update

Revision ID: 25a75dc1198a
Revises: 7d84746c7375
Create Date: 2024-05-06 00:55:08.164481

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '25a75dc1198a'
down_revision = '7d84746c7375'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
