"""Description of model changes

Revision ID: b51b94ec1db0
Revises: d7ef1e1567cf
Create Date: 2024-05-05 11:03:32.132852

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b51b94ec1db0'
down_revision = 'd7ef1e1567cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
