"""warehouse model update2

Revision ID: bc1946394fd5
Revises: 25a75dc1198a
Create Date: 2024-05-06 03:06:25.312056

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bc1946394fd5'
down_revision = '25a75dc1198a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
