"""Description of model changes

Revision ID: d7ef1e1567cf
Revises: e2412789c190
Create Date: 2024-05-05 10:53:04.603033

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd7ef1e1567cf'
down_revision = 'e2412789c190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('wholesale_price', sa.Integer(), nullable=False))
    op.add_column('item', sa.Column('retail_price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'retail_price')
    op.drop_column('item', 'wholesale_price')
    # ### end Alembic commands ###
